name: CI Pipeline - Basics

on:
  push:
    branches:
      - master

jobs:
  basic-check:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Download your repo code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Show where we are
      - name: Print working directory
        run: pwd

      # Step 3: List project files
      - name: List project files
        run: ls -la

      # Step 4: Confirm CI works
      - name: Success message
        run: echo "CI Level 3 completed successfully ðŸš€"
